### ISSUE TITLE
How to remove the blurry effect in the outputs for super resolution?

### ISSUE THREAD

**Issue by Josh00-Lu** [wyhuai/DDNM#9]
I followed the instructions in README.md and tried the 8x super resolution application on several test images using DDNM, here are my python commands.
```
python main.py --ni --simplified --config celeba_hq.yml --path_y celeba_hq --eta 0.85 --deg "sr_averagepooling" --deg_scale 8.0 --sigma_y 0 -i demo
```
The content of "celeba_hq.yml" is：
```
data:
    dataset: "CelebA_HQ"
    category: ""
    image_size: 256
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 32
    out_of_dist: false

model:
    type: "simple"
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

sampling:
    batch_size: 1
    
time_travel:
    T_sampling: 100
    travel_length: 1
    travel_repeat: 1
```

My inputs are:
<img width="256" alt="截屏2022-12-19 下午1 49 16" src="https://user-images.githubusercontent.com/74221638/208356694-6b80e4a3-2023-46f8-ad12-2e0443704171.png">

<img width="259" alt="image" src="https://user-images.githubusercontent.com/74221638/208356735-060d8726-7ac2-4f65-8215-101c9a872669.png">

The DDNM outputs are:
<img width="258" alt="image" src="https://user-images.githubusercontent.com/74221638/208356874-2c074aec-52e6-41c6-bff9-306fb660e705.png">

<img width="258" alt="image" src="https://user-images.githubusercontent.com/74221638/208356922-079e048e-d144-4b46-b065-1b0d6b2b28c1.png">

where blurring effect appears in the results. Is there any way to eliminate this effect?
